"""多厂商告警/状态码启发式知识库。"""

from __future__ import annotations

COMMON_ALARM_HINTS: dict[str, str] = {
    "emergency_stop": "急停按下，需现场复位",
    "over_voltage": "过压保护，检查电网/输出电压",
    "under_voltage": "欠压保护，检查输入电源",
    "over_current": "过流保护，检查负载与线缆",
    "over_temp": "过温保护，检查散热与环境温度",
    "insulation_fault": "绝缘故障，停止充电并排查线束",
    "connector_fault": "枪连接异常，检查电子锁/CC/CP",
    "bms_timeout": "BMS 通信超时，检查 CAN/协议版本",
    "meter_fault": "电表故障，核查计量模块",
    "door_open": "门禁打开，充电被禁止",
    "smoke": "烟感告警，立即停机排查",
}

_GENERIC_STATUS = {
    0: "空闲",
    1: "插枪/占用",
    2: "充电中",
    3: "完成",
    4: "故障",
    5: "离线/不可用",
    "idle": "空闲",
    "charging": "充电中",
    "fault": "故障",
    "offline": "离线",
    "Available": "可用",
    "Preparing": "准备中",
    "Charging": "充电中",
    "SuspendedEVSE": "桩端暂停",
    "SuspendedEV": "车端暂停",
    "Finishing": "结束中",
    "Reserved": "预约",
    "Unavailable": "不可用",
    "Faulted": "故障",
}


VENDOR_STATUS_MAP: dict[str, dict[int | str, str]] = {
    "xingxing": {
        0: "空闲",
        1: "插枪",
        2: "充电中",
        3: "充电完成",
        4: "故障",
        5: "预约",
        "idle": "空闲",
        "charging": "充电中",
        "fault": "故障",
        "offline": "离线",
    },
    "shenghong": {
        0: "空闲",
        1: "充电中",
        2: "故障",
        3: "离线",
        4: "完成",
    },
    "huawei": {
        "Idle": "空闲",
        "Occupied": "占用",
        "Charging": "充电中",
        "Faulted": "故障",
        "Unavailable": "不可用",
    },
    "infypower": {
        0: "待机",
        1: "握手",
        2: "充电",
        3: "结束",
        4: "故障",
    },
    "teld": _GENERIC_STATUS,
    "sgcc": _GENERIC_STATUS,
    "csg": _GENERIC_STATUS,
    "xiaoju": _GENERIC_STATUS,
    "aoneng": _GENERIC_STATUS,
    "putian": _GENERIC_STATUS,
    "kehua": _GENERIC_STATUS,
    "kstar": _GENERIC_STATUS,
    "abb": _GENERIC_STATUS,
    "evercharge": _GENERIC_STATUS,
    "kamaisi": _GENERIC_STATUS,
    "dakuyun": _GENERIC_STATUS,
    "youyichong": _GENERIC_STATUS,
    "nari": _GENERIC_STATUS,
    "zhichong": _GENERIC_STATUS,
    "anyue": _GENERIC_STATUS,
    "wallbox": _GENERIC_STATUS,
    "phoenix": _GENERIC_STATUS,
    "lvtong": _GENERIC_STATUS,
}
