"""科华充电桩与云平台通信协议 V4.09 知识库。"""

from __future__ import annotations

KH_PROTOCOL_VERSION = "V4.09"
KH_MAGIC = b"KH"  # 0x4B 0x48
KH_TAIL = 0x68
KH_HEADER_LEN = 34  # 起始帧头 … 枪号（不含信息域）

# 功能码 → (名称, 方向说明)
KH_CMD_NAMES: dict[int, str] = {
    0x01: "登录",
    0x81: "登录确认",
    0x02: "心跳",
    0x82: "心跳确认",
    0x03: "读取终端数据",
    0x83: "上传终端数据",
    0x04: "写终端数据",
    0x84: "写终端数据确认",
    0x05: "计费模型查询",
    0x85: "计费模型上报",
    0x06: "计费模型设置",
    0x86: "计费模型设置确认",
    0x09: "预约充电",
    0x89: "预约充电确认",
    0x0A: "启停充电",
    0x8A: "启停充电通知确认",
    0x0B: "启停充电结果",
    0x8B: "启停结果确认",
    0x0C: "刷卡请求",
    0x8C: "刷卡请求确认",
    0x0D: "实时数据上传",
    0x8D: "实时数据确认",
    0x0E: "历史充电记录",
    0x8E: "充电记录确认",
    0x0F: "历史告警",
    0x8F: "告警记录确认",
    0x10: "操作记录",
    0x90: "操作记录确认",
    0x11: "FTP升级指令",
    0x91: "FTP升级应答",
    0x12: "升级结果",
    0x92: "升级结果确认",
    0x13: "主动上传数据",
    0x93: "主动上传确认",
    0x16: "TCP升级请求",
    0x96: "TCP升级应答",
    0x17: "TCP升级数据",
    0x97: "TCP升级数据应答",
    0x1A: "升级结果上报",
    0x9A: "升级结果响应",
    0x1B: "对时",
    0x9B: "对时结果",
    0x1C: "金额补发",
    0x9C: "金额补发结果",
    0x1D: "VIN码启动请求",
    0x9D: "VIN码启动应答",
    0x1E: "密码启动请求",
    0x9E: "密码启动应答",
    0x1F: "尖峰平谷计费设置",
    0x9F: "尖峰平谷计费设置结果",
    0x20: "尖峰平谷计费查询",
    0xA0: "尖峰平谷计费查询结果",
    0x21: "功率请求",
    0xA1: "功率应答",
    0x22: "功率限制",
    0xA2: "功率限制结果",
    0x23: "离线规则查询",
    0xA3: "离线规则查询结果",
    0x24: "离线规则设置",
    0xA4: "离线规则设置结果",
    0x25: "离线规则删除",
    0xA5: "离线规则删除结果",
    0x30: "二维码设置",
    0xB0: "二维码设置结果",
    0x32: "获取实时数据",
    0xB2: "获取实时数据应答",
    0x35: "远程调试",
    0xB5: "远程调试应答",
    0x36: "远程调试结果",
    0xB6: "远程调试结果确认",
    0x37: "并机接触器次数查询",
    0xB7: "并机接触器次数应答",
    0x38: "系统重启",
    0xB8: "系统重启结果",
    0x39: "系统状态查询",
    0xB9: "系统状态应答",
    0x3A: "BMS数据上报",
    0xBA: "BMS数据确认",
    0x3B: "健康数据查询",
    0xBB: "健康数据应答",
    0x3C: "接触器状态查询",
    0xBC: "接触器状态应答",
}

KH_LOGIN_ACK: dict[int, str] = {
    0: "确认失败",
    1: "确认成功",
    2: "串号未注册",
    3: "设备类型未知",
    4: "帧长度错误",
    5: "帧校验码错误",
}

KH_CHARGE_WAY: dict[int, str] = {
    0: "卡充",
    1: "APP充",
    2: "在线卡充/VIN码充/密码",
    3: "蓝牙充",
}

KH_CHARGE_MODE: dict[int, str] = {
    0: "自动充电",
    1: "金额模式",
    2: "电量模式",
    3: "时间模式",
    4: "电流模式",
}

KH_CARD_TYPE: dict[int, str] = {
    0: "无卡充",
    1: "个人卡",
    2: "超级卡",
    3: "管理卡",
    4: "在线卡",
    5: "APP启动",
    6: "VIN码启动",
    7: "密码启动",
    8: "蓝牙启动",
}

KH_START_STOP_OP: dict[int, str] = {
    1: "充电启动",
    2: "充电停止",
    3: "放电启动",
    4: "放电停止",
}

KH_START_STRATEGY: dict[int, str] = {
    0: "充满为止",
    1: "时间控制充电",
    2: "金额控制充电",
    3: "电量控制充电",
    4: "电流控制充电",
}

KH_GUN_STATUS: dict[int, str] = {
    0: "空闲",
    1: "插枪",
    2: "充电等待",
    3: "启动中",
    4: "充电中",
    5: "重连",
    6: "等待接收BSD",
    7: "结算状态",
    8: "充电停机(A类故障)",
    9: "放电中",
    11: "预约状态",
    12: "平台预约状态",
    13: "未支付卡状态",
    14: "充电完成状态",
    15: "APP预约状态",
    16: "试用期到，停止服务",
}

KH_CAR_LINK: dict[int, str] = {
    0: "未连接",
    1: "已连接",
}

# 实时数据 TLV（表 64）
KH_RT_UNITS: dict[int, tuple[str, str, float | None]] = {
    # id: (name, label, scale)  scale=None 表示原值/特殊
    0x1003: ("session_id", "充电流水号", None),
    0x1004: ("charge_voltage", "充电电压", 0.1),
    0x1005: ("charge_current", "充电电流", 0.01),
    0x1006: ("charge_duration", "充电时长", 1.0),
    0x1007: ("charge_energy", "充电电量", 0.01),
    0x1008: ("total_amount", "充电总金额", 0.0001),
    0x1009: ("service_fee", "充电服务费", 0.0001),
    0x100A: ("remain_minutes", "剩余时间", 1.0),
    0x100B: ("meter_kwh", "当前电表读数", 0.01),
    0x100C: ("soc", "当前SOC", None),
    0x100D: ("bms_req_voltage", "BMS需求电压", 0.1),
    0x100E: ("bms_req_current", "BMS需求电流", 0.1),
    0x100F: ("input_a_voltage", "输入A电压", 0.1),
    0x1010: ("input_b_voltage", "输入B电压", 0.1),
    0x1011: ("input_c_voltage", "输入C电压", 0.1),
    0x1012: ("input_a_current", "输入A电流", 0.01),
    0x1013: ("input_b_current", "输入B电流", 0.01),
    0x1014: ("input_c_current", "输入C电流", 0.01),
    0x1015: ("active_power", "总有功功率", 0.01),
    0x1016: ("reactive_power", "总无功功率", 0.01),
    0x1017: ("gun_dc_pos_temp", "充电枪DC+温度", 0.1),
    0x1018: ("gun_dc_neg_temp", "充电枪DC-温度", 0.1),
    0x1019: ("batt_temp_max", "最高动力电池温度", 0.1),
    0x101A: ("batt_temp_min", "最低动力电池温度", 0.1),
    0x101B: ("alloc_power", "分配功率", 0.01),
    0x101C: ("vin", "VIN码", None),
    0x101D: ("card_type", "充电卡类型", None),
    0x101E: ("pwm", "PWM", None),
    0x101F: ("leak_current", "漏电电流", 0.01),
    0x1020: ("charge_discharge", "充放电状态", None),
}

# 主动上传 TLV（表 65，与实时表部分 ID 重叠时按功能码区分）
KH_ACTIVE_UNITS: dict[int, tuple[str, str]] = {
    0x1000: ("gun_status", "枪状态"),
    0x1001: ("car_link_status", "车辆连接状态"),
    0x1002: ("alarm_lo", "告警信息低字节"),
    0x1003: ("alarm_status", "告警状态"),
    0x1004: ("session_id", "充电流水号"),
    0x1005: ("fault_duty", "故障责任划分"),
    0x1006: ("alarm_hi", "告警信息高字节"),
    0x1030: ("card_no", "充电卡号"),
    0x1031: ("card_type", "充电卡类型"),
    0x1032: ("card_balance", "充电前卡余额"),
    0x1033: ("vin", "车辆VIN"),
    0x1034: ("plate_no", "车牌号"),
    0x1035: ("start_time", "充电开始时间"),
    0x1036: ("meter_before", "充电前电表读数"),
    0x1037: ("start_way", "充电启动方式"),
    0x1038: ("charge_mode", "充电模式"),
    0x1039: ("charge_mode_param", "充电模式参数"),
    0x103A: ("parking_status", "车位占用状态"),
    0x103B: ("online_status", "终端在线状态"),
}

KH_FIELD_LABELS: dict[str, str] = {
    "magic": "起始帧头",
    "frame_len": "帧长",
    "protocol_ver": "协议版本",
    "seq": "报文流水号",
    "device_type": "设备类型",
    "device_sn": "设备串号",
    "encrypt": "加密方式",
    "func_code": "功能码",
    "device_id": "设备ID",
    "gun_no": "枪号",
    "crc": "CRC16",
    "tail": "结束字节",
    "gun_count": "总枪数",
    "parent_sn": "父设备串号",
    "ack": "确认标识",
    "login_time": "登录时间",
    "heartbeat_seq": "心跳序号",
    "charge_way": "充电方式",
    "charge_mode": "充电模式",
    "card_type": "充电卡类型",
    "card_no": "充电卡号",
    "vin": "车辆VIN",
    "balance_before": "充电前余额",
    "max_voltage": "充电最高电压",
    "max_current": "充电最大电流",
    "charge_seconds": "充电时间",
    "energy_fee": "充电电费",
    "charge_energy": "充电电能",
    "meter_start": "充电开始电能",
    "meter_end": "充电结束电能",
    "soc_start": "开始SOC",
    "soc_end": "结束SOC",
    "paid": "是否付费",
    "stop_reason": "充电终止原因",
    "start_time": "充电开始时间",
    "end_time": "充电结束时间",
    "session_id": "充电流水号",
    "local_session_id": "本地存储流水号",
    "service_fee": "充电服务费",
    "total_fee": "总费用",
    "op_type": "操作类型",
    "strategy": "充电策略",
    "strategy_param": "充电策略参数",
    "alarm_point": "告警点",
    "alarm_start": "告警开始时间",
    "alarm_end": "告警结束时间",
}
