"""盛弘充电桩后台通信协议 V5.2B 知识库。"""

from __future__ import annotations

SH_PROTOCOL_VERSION = "V5.2B"

# CMD 奇数=平台下行，偶数=桩上行
SH_CMD_NAMES: dict[int, str] = {
    1: "平台下发整形工作参数",
    2: "桩应答整形参数设置/查询",
    3: "平台下发字符形参数",
    4: "桩应答字符形参数设置/查询",
    5: "平台下发控制命令",
    6: "桩应答控制命令",
    7: "平台下发开启充电",
    8: "桩应答开启充电",
    101: "平台应答心跳",
    102: "桩上传心跳",
    103: "平台应答状态信息",
    104: "桩上报状态信息",
    105: "平台应答签到",
    106: "桩签到上报",
    107: "平台应答告警",
    108: "桩告警上报",
    109: "平台应答启动完成",
    110: "桩上报启动完成",
    113: "平台查询最近一次分时电量",
    114: "桩应答最近一次分时电量",
    201: "平台应答充电记录(0.01kWh)",
    202: "桩上报充电记录(0.01kWh)",
    221: "平台应答充电记录(0.001kWh)",
    222: "桩上报充电记录(0.001kWh)",
    203: "平台应答账户查询",
    204: "桩上传账户查询",
    301: "平台应答 BMS 信息",
    302: "桩上报 BMS 信息",
    401: "平台查询历史充电记录",
    402: "桩上报历史充电记录",
    421: "平台查询历史充电记录(扩展)",
    422: "桩上报历史充电记录(扩展)",
    1101: "平台查询24时段电价",
    1102: "桩应答24时段电价",
    1103: "平台设置24时段电价",
    1104: "桩应答设置24时段电价",
    1105: "平台设置分时电价",
    1106: "桩应答设置分时电价",
    1107: "平台查询分时电价",
    1108: "桩回复分时电价",
    1401: "平台下发 FTP 升级",
    1402: "桩应答 FTP 升级",
}

SH_WORK_STATUS: dict[int, str] = {
    0: "空闲中",
    1: "正准备开始充电",
    2: "充电进行中",
    3: "充电结束",
    4: "启动失败",
    5: "预约状态",
    6: "系统故障（不能再充电）",
    7: "暂停充电",
}

SH_GUN_TYPE: dict[int, str] = {
    1: "直流枪",
    2: "交流枪",
}

SH_CHARGE_WAY: dict[int, str] = {
    0: "本地刷卡启动",
    1: "后台启动",
    2: "本地管理员启动",
    3: "远程 VIN 验证启动",
    4: "远程账号验证启动",
    5: "本地 VIN 验证启动",
    6: "本地鉴权码启动",
}

SH_STOP_STRATEGY: dict[int, str] = {
    0: "自动充满",
    1: "按时间充满",
    2: "按金额充满",
    3: "按电量充满",
}

SH_CAR_LINK: dict[int, str] = {
    0: "断开",
    1: "半连接",
    2: "连接",
}

# CMD104 主体字段（跳过前 4 字节预留后从桩编码开始）；单位按协议比例
# (name, size, kind) kind: ascii|u8|u16|u32|i16|temp|bcd_time|hex|skip
SH_CMD104_FIELDS: list[tuple[str, int, str]] = [
    ("pile_code", 32, "ascii"),
    ("gun_count", 1, "u8"),
    ("gun_no", 1, "u8"),
    ("gun_type", 1, "u8"),
    ("work_status", 1, "u8"),
    ("soc", 1, "u8"),
    ("alarm_code", 4, "u32"),
    ("car_link_status", 1, "u8"),
    ("session_fee", 4, "money"),
    ("internal_var2", 4, "skip"),
    ("internal_var3", 4, "skip"),
    ("dc_voltage", 2, "volt"),
    ("dc_current", 2, "curr"),
    ("bms_req_voltage", 2, "volt"),
    ("bms_req_current", 2, "curr"),
    ("bms_charge_mode", 1, "u8"),
    ("ac_a_voltage", 2, "volt"),
    ("ac_b_voltage", 2, "volt"),
    ("ac_c_voltage", 2, "volt"),
    ("ac_a_current", 2, "curr"),
    ("ac_b_current", 2, "curr"),
    ("ac_c_current", 2, "curr"),
    ("remain_minutes", 2, "u16"),
    ("charge_seconds", 4, "u32"),
    ("session_energy", 4, "energy01"),
    ("meter_before", 4, "energy01"),
    ("meter_now", 4, "energy01"),
    ("start_way", 1, "u8"),
    ("stop_strategy", 1, "u8"),
    ("strategy_param", 4, "u32"),
    ("reserve_flag", 1, "u8"),
    ("card_or_user", 32, "ascii"),
    ("reserve_timeout_min", 1, "u8"),
    ("start_or_reserve_time", 8, "bcd_time"),
    ("balance_before", 4, "money"),
    ("reserved38", 4, "skip"),
    ("charge_power", 4, "power01"),
]

SH_CMD106_FIELDS: list[tuple[str, int, str]] = [
    ("pile_code", 32, "ascii"),
    ("encrypt_support", 1, "u8"),
    ("soft_version", 4, "hex"),
    ("project_type", 2, "u16"),
    ("start_times", 4, "u32"),
    ("data_upload_mode", 1, "u8"),
    ("sign_interval_min", 2, "u16"),
    ("internal_mode", 1, "u8"),
    ("gun_count", 1, "u8"),
    ("heartbeat_interval", 1, "u8"),
    ("heartbeat_timeout_count", 1, "u8"),
    ("charge_record_count", 4, "u32"),
    ("system_time", 8, "bcd_time"),
]

SH_CMD102_FIELDS: list[tuple[str, int, str]] = [
    ("pile_code", 32, "ascii"),
    ("heartbeat_count", 2, "u16"),
    ("gun_plug_bits", 16, "hex"),
]

SH_CMD202_FIELDS: list[tuple[str, int, str]] = [
    ("pile_code", 32, "ascii"),
    ("gun_pos_type", 1, "u8"),
    ("gun_no", 1, "u8"),
    ("card_no", 32, "ascii"),
    ("start_time", 8, "bcd_time"),
    ("end_time", 8, "bcd_time"),
    ("duration_sec", 4, "u32"),
    ("soc_start", 1, "u8"),
    ("soc_end", 1, "u8"),
    ("stop_reason", 4, "u32"),
    ("session_energy", 4, "energy01"),
    ("meter_before", 4, "energy01"),
    ("meter_after", 4, "energy01"),
    ("session_money", 4, "money"),
    ("internal_index", 4, "u32"),
]

SH_FIELD_LABELS: dict[str, str] = {
    "pile_code": "充电桩编码",
    "gun_count": "充电枪数量",
    "gun_no": "枪号/枪序号",
    "gun_type": "枪类型",
    "work_status": "工作状态",
    "soc": "当前 SOC",
    "alarm_code": "当前最高告警编码",
    "car_link_status": "车连接状态",
    "session_fee": "本次充电累计充电费",
    "dc_voltage": "直流输出电压",
    "dc_current": "直流输出电流",
    "bms_req_voltage": "BMS 需求电压",
    "bms_req_current": "BMS 需求电流",
    "session_energy": "本次充电累计电量",
    "charge_seconds": "充电时长(秒)",
    "start_way": "启动充电方式",
    "stop_strategy": "充电策略",
    "charge_power": "充电功率",
    "card_or_user": "卡号/用户标识",
    "start_or_reserve_time": "预约/开始充电时间",
    "system_time": "当前系统时间",
    "encrypt_support": "是否支持加密",
    "soft_version": "充电桩软件版本",
    "sign_interval_min": "签到间隔(分钟)",
    "charge_record_count": "充电记录数量",
    "heartbeat_count": "心跳序号",
    "gun_plug_bits": "插枪状态位图",
    "gun_pos_type": "枪位类型",
    "card_no": "充电卡号",
    "start_time": "充电开始时间",
    "end_time": "充电结束时间",
    "duration_sec": "充电时长",
    "soc_start": "开始 SOC",
    "soc_end": "结束 SOC",
    "stop_reason": "停止充电原因",
    "session_money": "本次充电金额",
    "meter_before": "充前电表读数",
    "meter_after": "充后电表读数",
    "meter_now": "当前电表读数",
}
