"""蔚景科技充电桩运营服务通信协议 V2.6（JSGF001—2017）知识库。"""

from __future__ import annotations

PROTOCOL_VERSION = "V2.6"
PROTOCOL_SPEC = "JSGF001—2017"

# 命令码：请求 -> (名称, 方向, 应答码或 None)
# 方向: pile->platform | platform->pile | both
WEIJING_CMDS: dict[int, tuple[str, str, int | None]] = {
    0x00: ("请求秘钥", "pile->platform", 0x80),
    0x80: ("请求秘钥应答", "platform->pile", None),
    0x01: ("登录", "pile->platform", 0x81),
    0x81: ("登录应答", "platform->pile", None),
    0x02: ("预约充电", "platform->pile", 0x82),
    0x82: ("预约充电应答", "pile->platform", None),
    0x03: ("预约充电取消", "platform->pile", 0x83),
    0x83: ("预约充电取消应答", "pile->platform", None),
    0x04: ("设备请求启动充电", "pile->platform", 0x84),
    0x84: ("设备启动充电应答", "platform->pile", None),
    0x05: ("设备结束充电", "pile->platform", 0x85),
    0x85: ("设备结束充电应答", "platform->pile", None),
    0x06: ("远程启动充电", "platform->pile", 0x86),
    0x86: ("远程启动充电应答", "pile->platform", None),
    0x07: ("远程结束充电", "platform->pile", 0x87),
    0x87: ("远程结束充电应答", "pile->platform", None),
    0x08: ("上传充电账单", "pile->platform", 0x88),
    0x88: ("上传充电账单应答", "platform->pile", None),
    0x09: ("上传充电进度", "pile->platform", None),
    0x0A: ("上传 BMS 参数", "pile->platform", 0x8A),
    0x8A: ("上传 BMS 参数应答", "platform->pile", None),
    0x0B: ("计费规则设置", "platform->pile", 0x8B),
    0x8B: ("计费规则设置应答", "pile->platform", None),
    0x0C: ("心跳", "pile->platform", 0x8C),
    0x8C: ("心跳应答", "platform->pile", None),
    0x0D: ("告警", "pile->platform", 0x8D),
    0x8D: ("告警应答", "platform->pile", None),
    0x0E: ("校时", "platform->pile", 0x8E),
    0x8E: ("校时应答", "pile->platform", None),
    0x1A: ("白名单设置", "platform->pile", 0x9A),
    0x9A: ("白名单设置应答", "pile->platform", None),
    0x1B: ("黑名单设置", "platform->pile", 0x9B),
    0x9B: ("黑名单设置应答", "pile->platform", None),
    0x1C: ("二维码请求", "pile->platform", 0x9C),
    0x9C: ("二维码请求应答", "platform->pile", None),
    0x1D: ("远程功率调控", "platform->pile", 0x9D),
    0x9D: ("远程功率调控应答", "pile->platform", None),
    0x1E: ("远程升级", "platform->pile", 0x9E),
    0x9E: ("远程升级应答", "pile->platform", None),
    0x1F: ("请求升级包数据", "pile->platform", 0x9F),
    0x9F: ("请求升级包数据应答", "platform->pile", None),
    0x20: ("升级结果汇报", "pile->platform", 0xA0),
    0xA0: ("升级结果汇报应答", "platform->pile", None),
    0x21: ("远程控制", "platform->pile", 0xA1),
    0xA1: ("远程控制应答", "pile->platform", None),
    0x22: ("远程设置主站地址", "platform->pile", 0xA2),
    0xA2: ("远程设置主站地址应答", "pile->platform", None),
    0x23: ("充电盒子心跳", "pile->platform", 0xA3),
    0xA3: ("充电盒子心跳应答", "platform->pile", None),
    0x24: ("设备动态参数", "pile->platform", 0xA4),
    0xA4: ("设备动态参数应答", "platform->pile", None),
    0x25: ("解密出错", "platform->pile", None),
    0x26: ("查询用户余额", "pile->platform", 0xA6),
    0xA6: ("查询用户余额应答", "platform->pile", None),
    0x30: ("召测车辆充放电信息", "platform->pile", 0xB0),
    0xB0: ("召测车辆充放电信息应答", "pile->platform", None),
    0x31: ("启动/设置/调整充放电计划", "platform->pile", 0xB1),
    0xB1: ("充放电计划应答", "pile->platform", None),
    0x32: ("放电计费规则设置", "platform->pile", 0xB2),
    0xB2: ("放电计费规则设置应答", "pile->platform", None),
    0x33: ("上传充放电进度", "pile->platform", 0xB3),
    0xB3: ("上传充放电进度应答", "platform->pile", None),
    0x34: ("提前停止充放电计划", "platform->pile", 0xB4),
    0xB4: ("停止充放电计划应答", "pile->platform", None),
    0x35: ("上报放电账单", "pile->platform", 0xB5),
    0xB5: ("上报放电账单应答", "platform->pile", None),
    0x38: ("计费设置(无尖峰平谷)", "platform->pile", 0xB8),
    0xB8: ("计费设置(无尖峰平谷)应答", "pile->platform", None),
}

WEIJING_GUN_STATUS: dict[int, str] = {
    0: "空闲",
    1: "已插枪未充电",
    2: "充电中",
    3: "充电结束未拔枪",
    4: "预约中",
    5: "故障",
    6: "暂停中",
    7: "放电中",
}

WEIJING_PILE_TYPE: dict[int, str] = {
    1: "交流充电桩",
    2: "直流充电桩",
}

WEIJING_ENCRYPT: dict[int, str] = {
    0: "不加密",
    1: "AES",
    2: "SM4",
}

WEIJING_CHARGE_WAY: dict[int, str] = {
    1: "刷卡",
    2: "APP",
    3: "VIN",
    4: "账号密码",
    0x50: "离线充电后上报",
    0x55: "并枪副枪",
}

WEIJING_CHARGE_STRATEGY: dict[int, str] = {
    0: "自动充满",
    1: "自动充满",
    2: "按金额",
    3: "按时间",
    4: "按电量",
}

WEIJING_REMOTE_START_RESULT: dict[int, str] = {
    0: "成功",
    1: "枪被预约",
    2: "枪未插好",
    3: "枪充电中",
    4: "枪故障",
    5: "桩故障",
    6: "BMS通讯故障",
    7: "枪号错误",
    9: "其他",
}

WEIJING_FIELD_LABELS: dict[str, str] = {
    "start_flag": "起始标志",
    "cmd": "命令码",
    "seq": "消息序号",
    "pile_code_len": "设备编号长度",
    "pile_code": "设备编号",
    "encrypt_flag": "加密标志",
    "body_len": "消息体长度",
    "body_hex": "消息体十六进制",
    "crc16": "帧校验",
    "crc16_calc": "计算校验",
    "protocol_version": "协议版本",
    "pile_type": "桩类型",
    "rated_power": "额定功率",
    "gun_count": "充电枪数量",
    "fee_model_id": "计费规则ID",
    "fee_model_ver": "计费规则版本号",
    "operator_code": "运营商编码",
    "password": "密码",
    "software_ver": "软件版本",
    "hardware_ver": "硬件版本",
    "comm_protocol_ver": "通信协议版本",
    "login_result": "登录结果",
    "gun_no": "枪号",
    "gun_status": "枪状态",
    "server_time": "服务器时间",
    "trade_no": "订单号",
    "charge_way": "充电方式",
    "card_no": "卡号",
    "vin": "VIN码",
    "soc": "SOC",
    "start_time": "开始时间",
    "end_time": "结束时间",
    "precision": "数据精度位",
    "charge_energy": "充电电量",
    "jian_energy": "尖时电量",
    "feng_energy": "峰时电量",
    "ping_energy": "平时电量",
    "gu_energy": "谷时电量",
    "charge_money": "充电费金额",
    "service_money": "服务费金额",
    "reserve_money": "预约费金额",
    "parking_money": "停车费金额",
    "charger_temp": "充电机温度",
    "gun_temp": "枪头温度",
    "input_voltage": "输入电压",
    "input_current": "输入电流",
    "output_voltage": "输出电压",
    "output_current": "输出电流",
    "need_voltage": "电压需求",
    "need_current": "电流需求",
    "charge_strategy": "充电策略",
    "strategy_data": "策略数据",
    "stop_code": "充电停止码",
    "balance": "用户余额",
    "start_result": "启动结果",
    "key_len": "秘钥长度",
    "aes_key": "秘钥",
}
