"""云快充平台协议 V1.7 知识库。"""

from __future__ import annotations

PROTOCOL_VERSION = "V1.7"

# 英文字段名 -> 中文展示名
YKC_FIELD_LABELS: dict[str, str] = {
    "start_flag": "起始标志",
    "data_length": "数据长度",
    "seq": "序列号",
    "encrypt_flag": "加密标志",
    "frame_type": "帧类型",
    "protocol_version": "协议版本",
    "crc16": "帧校验",
    "crc16_calc": "计算校验",
    "body": "消息体",
    "body_hex": "消息体十六进制",
    "body_tail": "未识别尾部",
    "pile_code": "桩编号",
    "pile_type": "桩类型",
    "gun_count": "充电枪数量",
    "comm_protocol_ver": "通信协议版本",
    "software_ver": "程序版本",
    "network_type": "网络链接类型",
    "sim": "SIM卡号",
    "operator": "运营商",
    "login_result": "登陆结果",
    "gun_no": "枪号",
    "gun_status": "枪状态",
    "fee_model_no": "计费模型编号",
    "verify_result": "验证结果",
    "trade_no": "交易流水号",
    "status": "状态",
    "gun_homed": "枪是否归位",
    "gun_plugged": "是否插枪",
    "output_voltage": "输出电压",
    "output_current": "输出电流",
    "output_power": "输出功率",
    "gun_cable_temp": "枪线温度",
    "gun_cable_code": "枪线编码",
    "soc": "SOC",
    "battery_max_temp": "电池组最高温度",
    "charge_time_min": "累计充电时间",
    "remain_time_min": "剩余时间",
    "charge_energy": "充电度数",
    "loss_energy": "计损充电度数",
    "charged_amount": "已充金额",
    "hardware_fault": "硬件故障",
    "start_way": "启动方式",
    "need_password": "是否需要密码",
    "account_or_card": "账号或物理卡号",
    "password_md5": "输入密码",
    "vin": "VIN码",
    "logic_card": "逻辑卡号",
    "physical_card": "物理卡号",
    "balance": "账户余额",
    "auth_ok": "鉴权成功标志",
    "auth_fail_reason": "失败原因",
    "start_result": "启动结果",
    "fail_reason": "失败原因",
    "stop_result": "停止结果",
    "confirm_result": "确认结果",
    "meter_no": "电表表号",
    "meter_cipher": "电表密文",
    "meter_proto_ver": "电表协议版本号",
    "encrypt_type": "加密标记",
    "jian_price": "尖单价",
    "jian_energy": "尖电量",
    "jian_loss_energy": "计损尖电量",
    "jian_money": "尖金额",
    "feng_price": "峰单价",
    "feng_energy": "峰电量",
    "feng_loss_energy": "计损峰电量",
    "feng_money": "峰金额",
    "ping_price": "平单价",
    "ping_energy": "平电量",
    "ping_loss_energy": "计损平电量",
    "ping_money": "平金额",
    "gu_price": "谷单价",
    "gu_energy": "谷电量",
    "gu_loss_energy": "计损谷电量",
    "gu_money": "谷金额",
    "meter_start": "电表总起值",
    "meter_end": "电表总止值",
    "total_energy": "总电量",
    "total_loss_energy": "计损总电量",
    "total_money": "消费金额",
    "txn_flag": "交易标识",
    "txn_time": "交易日期时间",
    "start_time": "开始时间",
    "end_time": "结束时间",
    "stop_reason": "停止原因",
}

# frame_type -> (name, direction, brief)
YKC_FRAME_TYPES: dict[int, tuple[str, str, str]] = {
    0x01: ("充电桩登录认证", "pile->platform", "上电/重连登录"),
    0x02: ("登录认证应答", "platform->pile", "登录结果"),
    0x03: ("充电桩心跳包", "pile->platform", "链路保活"),
    0x04: ("心跳包应答", "platform->pile", "心跳应答"),
    0x05: ("计费模型验证请求", "pile->platform", "校验计费模型"),
    0x06: ("计费模型验证请求应答", "platform->pile", "计费模型是否一致"),
    0x09: ("充电桩计费模型请求", "pile->platform", "请求计费模型"),
    0x0A: ("计费模型请求应答", "platform->pile", "下发计费模型"),
    0x12: ("读取实时监测数据", "platform->pile", "召测实时数据"),
    0x13: ("上传实时监测数据", "pile->platform", "实时监测上报"),
    0x15: ("充电握手", "pile->platform", "BMS 握手"),
    0x17: ("参数配置", "pile->platform", "BMS 参数配置"),
    0x19: ("充电结束", "pile->platform", "BMS 充电结束"),
    0x1B: ("错误报文", "pile->platform", "BMS 错误"),
    0x1D: ("充电阶段 BMS 中止", "pile->platform", "BMS 中止"),
    0x21: ("充电阶段充电机中止", "pile->platform", "充电机中止"),
    0x23: ("充电过程 BMS 需求与充电机输出", "pile->platform", "BMS 需求/输出"),
    0x25: ("充电过程 BMS 信息", "pile->platform", "BMS 信息"),
    0x31: ("充电桩主动申请启动充电", "pile->platform", "刷卡/VIN 申请启机"),
    0x32: ("运营平台确认启动充电", "platform->pile", "启机鉴权结果"),
    0x33: ("远程启机命令回复", "pile->platform", "远程启机结果"),
    0x34: ("运营平台远程控制启机", "platform->pile", "APP 远程启机"),
    0x35: ("远程停机命令回复", "pile->platform", "远程停机结果"),
    0x36: ("运营平台远程停机", "platform->pile", "远程停机"),
    0x3B: ("交易记录（旧版 V1.5）", "pile->platform", "兼容旧交易记录帧"),
    0x3D: ("交易记录", "pile->platform", "结算账单上送"),
    0x40: ("交易记录确认", "platform->pile", "账单接收确认"),
    0x41: ("余额更新应答", "pile->platform", "余额更新结果"),
    0x42: ("远程账户余额更新", "platform->pile", "更新账户余额"),
    0x43: ("离线卡数据同步应答", "pile->platform", "离线卡同步结果"),
    0x44: ("离线卡数据同步", "platform->pile", "下发离线卡"),
    0x45: ("离线卡数据清除应答", "pile->platform", "清除结果"),
    0x46: ("离线卡数据清除", "platform->pile", "清除离线卡"),
    0x47: ("离线卡数据查询应答", "pile->platform", "查询结果"),
    0x48: ("离线卡数据查询", "platform->pile", "查询离线卡"),
    0x51: ("充电桩工作参数设置应答", "pile->platform", "参数设置结果"),
    0x52: ("充电桩工作参数设置", "platform->pile", "工作参数下发"),
    0x55: ("对时设置应答", "pile->platform", "对时应答"),
    0x56: ("对时设置", "platform->pile", "平台对时"),
    0x57: ("计费模型应答", "pile->platform", "计费模型设置结果"),
    0x58: ("计费模型设置", "platform->pile", "下发费率模型"),
    0x61: ("地锁数据上送", "pile->platform", "地锁状态"),
    0x62: ("遥控地锁升锁与降锁命令", "platform->pile", "地锁控制"),
    0x63: ("充电桩返回数据（上行）", "pile->platform", "地锁控制应答"),
    0x91: ("远程重启应答", "pile->platform", "重启结果"),
    0x92: ("远程重启", "platform->pile", "远程重启"),
    0x93: ("远程更新应答", "pile->platform", "OTA 结果"),
    0x94: ("远程更新", "platform->pile", "OTA 下发"),
    0xA1: ("充电桩主动申请并充充电", "pile->platform", "并充申请"),
    0xA2: ("运营平台确认并充启动充电", "platform->pile", "并充鉴权"),
    0xA3: ("远程并充启机命令回复", "pile->platform", "并充启机结果"),
    0xA4: ("运营平台远程控制并充启机", "platform->pile", "并充远程启机"),
}


# 0x31 / 0xA1 申请启机
YKC_APPLY_START_WAY: dict[int, str] = {
    0x01: "刷卡启动",
    0x02: "账号启动",
    0x03: "VIN 码启动",
}


# 交易记录交易标识
YKC_TXN_FLAG: dict[int, str] = {
    0x01: "app 启动",
    0x02: "卡启动",
    0x04: "离线卡启动",
    0x05: "VIN 码启动",
}


YKC_GUN_STATUS: dict[int, str] = {
    0x00: "离线",
    0x01: "故障",
    0x02: "空闲",
    0x03: "充电",
}


YKC_HOMED: dict[int, str] = {
    0x00: "否",
    0x01: "是",
    0x02: "未知",
}


# 远程启机失败原因（0x33）
YKC_START_FAIL_REASON: dict[int, str] = {
    0x00: "无",
    0x01: "设备编号不匹配",
    0x02: "枪已在充电",
    0x03: "设备故障",
    0x04: "设备离线",
    0x05: "未插枪",
}


# 鉴权失败原因（0x32）
YKC_AUTH_FAIL_REASON: dict[int, str] = {
    0x01: "账户不存在",
    0x02: "账户冻结",
    0x03: "账户余额不足",
    0x04: "该卡存在未结账记录",
    0x05: "桩停用",
    0x06: "该账户不能在此桩上充电",
    0x07: "密码错误",
    0x08: "电站电容不足",
    0x09: "系统中 VIN 码不存在",
    0x0A: "该桩存在未结账记录",
    0x0B: "该桩不支持刷卡",
}


YKC_STOP_CMD_FAIL: dict[int, str] = {
    0x00: "无",
    0x01: "设备编号不匹配",
    0x02: "枪未处于充电状态",
    0x03: "其他",
}


# 附录停止原因（常用全集）
YKC_STOP_REASON: dict[int, str] = {
    0x40: "结束充电，APP 远程停止",
    0x41: "结束充电，SOC 达到 100%",
    0x42: "结束充电，充电电量满足设定条件",
    0x43: "结束充电，充电金额满足设定条件",
    0x44: "结束充电，充电时间满足设定条件",
    0x45: "结束充电，手动停止充电",
    0x4A: "充电启动失败，充电桩控制系统故障",
    0x4B: "充电启动失败，控制导引断开",
    0x4C: "充电启动失败，断路器跳位",
    0x4D: "充电启动失败，电表通信中断",
    0x4E: "充电启动失败，余额不足",
    0x4F: "充电启动失败，充电模块故障",
    0x50: "充电启动失败，急停开入",
    0x51: "充电启动失败，防雷器异常",
    0x52: "充电启动失败，BMS 未就绪",
    0x53: "充电启动失败，温度异常",
    0x54: "充电启动失败，电池反接故障",
    0x55: "充电启动失败，电子锁异常",
    0x56: "充电启动失败，合闸失败",
    0x57: "充电启动失败，绝缘异常",
    0x59: "充电启动失败，接收 BMS 握手报文 BHM 超时",
    0x5A: "充电启动失败，接收 BRM 超时",
    0x5B: "充电启动失败，接收 BCP 超时",
    0x5C: "充电启动失败，接收 BRO AA 超时",
    0x5D: "充电启动失败，接收 BCS 超时",
    0x5E: "充电启动失败，接收 BCL 超时",
    0x5F: "充电启动失败，接收 BSM 超时",
    0x6A: "充电异常中止，系统闭锁",
    0x6B: "充电异常中止，导引断开",
    0x6C: "充电异常中止，断路器跳位",
    0x6D: "充电异常中止，电表通信中断",
    0x6E: "充电异常中止，余额不足",
    0x6F: "充电异常中止，交流保护动作",
    0x70: "充电异常中止，直流保护动作",
    0x71: "充电异常中止，充电模块故障",
    0x72: "充电异常中止，急停开入",
    0x73: "充电异常中止，防雷器异常",
    0x74: "充电异常中止，温度异常",
    0x75: "充电异常中止，输出异常",
    0x76: "充电异常中止，充电无流",
    0x77: "充电异常中止，电子锁异常",
    0x79: "充电异常中止，总充电电压异常",
    0x7A: "充电异常中止，总充电电流异常",
    0x7B: "充电异常中止，单体充电电压异常",
    0x7C: "充电异常中止，电池组过温",
    0x90: "未知原因停止",
}


YKC_HARDWARE_FAULT_BITS: dict[int, str] = {
    0: "急停按钮动作故障",
    1: "无可用整流模块",
    2: "出风口温度过高",
    3: "交流防雷故障",
    4: "交直流模块 DC20 通信中断",
    5: "绝缘检测模块 FC08 通信中断",
    6: "电度表通信中断",
    7: "读卡器通信中断",
    8: "RC10 通信中断",
    9: "风扇调速板故障",
    10: "直流熔断器故障",
    11: "高压接触器故障",
    12: "门打开",
}
